CATEGORY_ID_BY_CATEGORY = {
  'TARGET': 13,
  'LOCALE': 11,
  'EVENT': 12,
}

# TODO(ISSUE-12): Dynamically update version so it doesn't mistakenly get stale.
DKP_SCRIPT_VERSION_TAG = 'Generated by DKP script v0.0.8.\nhttps://github.com/chuuwee/lineage'