from datetime import datetime
import pickle
import pytz
import requests
import urllib.parse
from get_event_categories import get_event_categories, print_event_category

event_categories = get_event_categories()
for event_category in event_categories:
  print_event_category(event_category)

event_category_id_raw: str = input('select an event type: ')
if not event_category_id_raw.isdigit():
  raise ValueError('Invalid category id')
event_category_id = int(event_category_id_raw)
event_name: str = input('name your event: ')

# Load the serialized cookies from a file
with open('cookies.pkl', 'rb') as f:
  cookies = pickle.load(f)

# Set the timezone to Central Standard Time
eastern = pytz.timezone('US/Central')

# Get the current time in Eastern Standard Time
now = datetime.now(eastern)

# Format the current time as a string in the desired format
time_str = now.strftime("%m/%d/%Y %I:%M%p").lower()

url: str = 'http://lineageeq.dkpsystem.com/editevent.php'
headers: dict[str, str] = {
  'content-type': 'application/x-www-form-urlencoded',
}

# set the form data for the request
data = urllib.parse.urlencode({
  'eventcategoryid': event_category_id,
  'game': 'eq',
  'lanparty': event_name,
  'securitylevelid': 5,
  'rosterid': 1,
  'signupsecuritylevelid': 5,
  'day': time_str,
  'description': 'Generated by DKP script.',
  'submit': 'Submit',
})

# send the request
response = requests.post(url, cookies=cookies, headers=headers, data=data, allow_redirects=False, verify=False)
