from datetime import datetime
import pickle
import pytz
import requests
import urllib.parse

# Load the serialized cookies from a file
with open('cookies.pkl', 'rb') as f:
  cookies = pickle.load(f)

# Set the timezone to Central Standard Time
eastern = pytz.timezone('US/Central')

# Get the current time in Eastern Standard Time
now = datetime.now(eastern)

# Format the current time as a string in the desired format
date_str = now.strftime("%M/%D/%Y").lower()

url: str = 'http://lineageeq.dkpsystem.com/admineqdkpupload.php'
headers: dict[str, str] = {
  'content-type': 'application/x-www-form-urlencoded',
}

# set the form data for the request
data = urllib.parse.urlencode({
  'server': 'P99 Green',
  # Need to sort out how to retrieve this reliably for recently created events.
  'lanpartyid': 14,
  'date': date_str,
  'dkpsystemid': 1,
  'pointtype': 'straight',
  'points': 1,
  'description': 'Generated by DKP script.',
  'playername[0]': 'bob',
  'class[0]': 'Magician',
  'race[0]': '',
  # Appears that level is irrelevant. Also, the payload for each array element
  # needs to be full.
  'level[0]': 60,
  'raidmember[0]': 0,
  'altmember[0]': '',
  'indivpoints[0]': '',
  'playername[1]': 'cindy',
  'class[1]': 'Bard',
  'race[1]':  '',
  'level[1]': 60,
  'raidmember[1]': 0,
  'altmember[1]': '',
  'indivpoints[1]': '',
  'process': 'Submit This Raid',
  'game': 'eq',
})

print(data)

# send the request
response = requests.post(url, cookies=cookies, headers=headers, data=data, allow_redirects=False, verify=False)
