from datetime import datetime
import pickle
import pytz
import requests
import urllib.parse
from create_event import create_event
from monitor_log import get_raid_attendance_payload

# Load the serialized cookies from a file
with open('cookies.pkl', 'rb') as f:
  cookies = pickle.load(f)

# Set the timezone to Central Standard Time
eastern = pytz.timezone('US/Central')

# Get the current time in Eastern Standard Time
now = datetime.now(eastern)

# Format the current time as a string in the desired format
date_str = now.strftime("%M/%D/%Y").lower()

url: str = 'http://lineageeq.dkpsystem.com/admineqdkpupload.php'
headers: dict[str, str] = {
  'content-type': 'application/x-www-form-urlencoded',
}

event = create_event()
char_payload = get_raid_attendance_payload()

# set the form data for the request
data = urllib.parse.urlencode({
  'server': 'P99 Green',
  # Need to sort out how to retrieve this reliably for recently created events.
  'lanpartyid': event['id'],
  'date': date_str,
  'dkpsystemid': 1,
  'pointtype': 'straight',
  'points': 1,
  'description': 'Generated by DKP script.',
  'process': 'Submit This Raid',
  'game': 'eq',
  **char_payload
})

# send the request
response = requests.post(url, cookies=cookies, headers=headers, data=data, allow_redirects=False, verify=False)
